### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by blop** [devplayer0/docker-net-dhcp#14]
Hello!

For some reason I had to perform the following setting in order to have the DHCP client working.
sysctl -w net.bridge.bridge-nf-call-iptables=0

Otherwise I kept having the following error : 
NetworkDriver.CreateEndpoint: failed to get initial IP address via DHCP: context deadline exceeded.

;-)

**Comment by blop** [comment]
You can also add a docker-compose example like : 

```
networks:
    my-dhcp-net:
        driver: ghcr.io/devplayer0/docker-net-dhcp:release-linux-amd64
        driver_opts:
            bridge: "my-bridge"
            lease_timeout: "60s"
        ipam:
            driver: "null"
```
